### ISSUE TITLE
Problem with UPS and Uclip

### ISSUE THREAD

**Issue by guillaume-dorczynski** [Foohy/gm-rollercoaster#15]
Hi there,

First let me tell you that your addon is fantastic. However I have 2 issues with it:

Before anything, you have to install ULX, ULib, Uclip, and UPS. Make sure you are a normal player, not an admin or superadmin. Basically, you have nothing to do but put those addons in the addons folder of your server.

Link to these addons: https://github.com/Nayruden/Ulysses

Now for the problems:

1) There is a problem with this addon and UPS (Ulysses Prop Share). I can spawn tracks etc, but after spawning more than the two first "balls", I'm unable to pick them with the physgun to move them around. UPS says I'm the owner of the ball, but I can't pick it up with the physgun and UPS plays the "denied" sound. Also, when looking at the track itself (not the ball) UPS says the owner is the World.

Here is how to reproduce.
- Select any kind of track (Normal, Home, Launch, etc), and spawn 2 "balls" of the same kind. You will be able to pick them with physgun.
- Spawn a third ball. You are now unable to pick any of the three balls.

2) A less annoying problem but still: with Uclip, normally I can noclip my own props. But I'm unable to noclip the balls, even UPS says I'm the owner. As said in the first problem, the tracks are owned by the World, which also disallow noclipping them. I would like to be able to noclip everything created by this addon if I'm the owner of the rollercoaster.

I hope those 2 problems can be fixed ;) Thanks in advance.

**Comment by Foohy** [comment]
Hey, sorry it took so long, I've been busy with school stuff.
Should be fixed in the newest revision (I'll push to workshop soon)

**Comment by guillaume-dorczynski** [comment]
Thanks, it seem to be fixed ;)
