### ISSUE TITLE
Game crash when trying to create Brakes or Speedup tracks

### ISSUE THREAD

**Issue by guillaume-dorczynski** [Foohy/gm-rollercoaster#16]
Hi,

This was tested on a clean dedicated server with no other addons, to make sure it wasn't a conflict with something else. It might be related to the recent gmod update?

Try to create a Brakes track, or Speedup track. If you create the 2 balls really close to each other (like if they are almost touching each other), this will spam the console with this error:

```
TEST [lua/includes/modules/matrix2.lua][lua/includes/modules/hook.lua]
TEST [lua/includes/modules/quaternion.lua][lua/includes/modules/hook.lua]
TEST [lua/includes/modules/vector2.lua][lua/includes/modules/hook.lua]
TEST [lua/includes/modules/vector3.lua][lua/includes/modules/hook.lua]
TEST [lua/includes/modules/von.lua][lua/includes/modules/hook.lua]

[ERROR] addons/lua_rollercoasters_104508032/lua/entities/coaster_node/cl_init.lua:230: attempt to get length of a nil value
  1. UpdateWheelPositions - addons/lua_rollercoasters_104508032/lua/entities/coaster_node/cl_init.lua:230
   2. WheelModelThink - addons/lua_rollercoasters_104508032/lua/entities/coaster_node/cl_init.lua:867
    3. DrawTrack - addons/lua_rollercoasters_104508032/lua/entities/coaster_node/cl_init.lua:787
     4. v - addons/lua_rollercoasters_104508032/lua/autorun/coastermanager.lua:367
      5. unknown - lua/includes/modules/hook.lua:84
```

However, if you create the 2 balls with a greater distance between them, then it will crash the game instantly (not the server, just the client).

And after that, if you try rejoin the server and your props are still here, you will most likely crash again instantly, and if not, then try to pickup the ball with the physgun, it should crash again.

It didn't happen with the previous version, before I updated to test your fix for UPS.

Thanks for fixing already ;)

PS: I just saw it was already reported on the Workshop, but I hope the details I gave, will help you ;)

**Comment by Foohy** [comment]
Alright hopefully fixed. I recoded the wheel system a bit because it was a bit icky, so double check to make sure I didn't forget something or it errors.

Thanks!

**Comment by guillaume-dorczynski** [comment]
It's no longer crashing so thanks a lot ;)

There is still an error when the balls are spawned really close to each other ( = when the space between balls is small enough that it "doesn't bother" placing a wheel between) This will most likely never happen when building a rollercoaster, but still, you should fix it ;)

```
[ERROR] addons/lua_rollercoasters_104508032/lua/entities/coaster_node/cl_init.lua:780: attempt to get length of a nil value
  1. UpdateWheelPositions - addons/lua_rollercoasters_104508032/lua/entities/coaster_node/cl_init.lua:780
   2. SetOutdated - addons/lua_rollercoasters_104508032/lua/entities/coaster_node/cl_init.lua:304
    3. OnNetworkVarChanged - addons/lua_rollercoasters_104508032/lua/entities/coaster_node/cl_init.lua:979
     4. NetworkVarCallbackThink - addons/lua_rollercoasters_104508032/lua/entities/coaster_node/cl_init.lua:953
      5. unknown - addons/lua_rollercoasters_104508032/lua/entities/coaster_node/cl_init.lua:1030
```

To fix it, I had to replace in cl_init.lua, line 779:

```
if Controller.Wheels != nil then
```

by

```
if Controller.Wheels[segment] != nil then
```

**Comment by Foohy** [comment]
Ah you're exactly right! Fixed.
