### ISSUE TITLE
Giant cans appearing at the end of the track

### ISSUE THREAD

**Issue by ghost** [Foohy/gm-rollercoaster#2]
Hello everyone,

I just installed the addon and it seems to work fine, however there are those giant can-like object at the two ends of the track. They seem quiet oversized and one of them disappears when taking out the camera tool.

http://imgur.com/a/1ENXV

Does anyone know what this is about?

**Comment by Foohy** [comment]
Alright fixed, those were the hidden nodes (well, "hidden") at the start and end of the track that are automatically created (since the spline requires 4 points). I'm not exactly sure why they were massive, but they shouldn't have been drawing in the first place.
