### ISSUE TITLE
Floating coaster duplicate in sky

### ISSUE THREAD

**Issue by SparkZZZ** [Foohy/gm-rollercoaster#3]
Don't know if you already know about this or not, but after creating my coaster I can see a ghost of it up in the sky.

See here: 
http://cloud-2.steampowered.com/ugc/594725347967680501/6B58768B0D8FE508CB27DA8A530AF8C506C64793/

I can try reproducing it again if you need me to. It might have to do with the map or something. I was just playing on the new gm_flatgrass.

**Comment by Foohy** [comment]
That's actually the map's fault. Any prop you spawn is seen above the skybox because garry has the actual skybox placed below the map.
![Normal Proper](http://img41.imageshack.us/img41/8061/screenshot2012072722455.png)
