### ISSUE TITLE
Lua error when building clientside mesh...

### ISSUE THREAD

**Issue by alanmock** [Foohy/gm-rollercoaster#5]
Hi, today was my first day jumping into the gmod13 beta and the first mod I got was the lua coaster! Everything was going fine until I tried "Building clientside mesh..." and I got a lua error, here is the log:

Building clientside mesh...
Compiling with GenType: Metal Track
[lua/entities\coaster_node\cl_init.lua:390] attempt to index a nil value    AngleAt lua/entities\coaster_node\cl_init.lua:390
    Generate    lua/autorun\tracktypes\cl_track_metal.lua:161
    UpdateClientMesh    lua/entities\coaster_node\cl_init.lua:368
    ?   lua/entities\coaster_node\cl_init.lua:311
    unknown lua/includes/modules/concommand.lua:69
    unknown (tail call):-1

just figured I would let you know, I would really like to make a nice roller coaster but with this error it is definitely not going to happen haha.

**Comment by Foohy** [comment]
Fixed (hopefully)

**Comment by alanmock** [comment]
Yay! For a short time I was getting a different error but now its working fine, thanks!!!
