### ISSUE TITLE
Having trouble saving my game?

### ISSUE THREAD

**Issue by Thepootisman** [Foohy/gm-rollercoaster#7]
Firstly, I want to say I absolutely LOVE this mod, much love to Foohy!
Secondly; Every time I try to save my world, Lua coaster mod keeps saying:

[saverestore.SaveGlobal] Error saving global state

What do? :c

**Comment by Foohy** [comment]
Aha! Before saverestore said absolutely nothing at all! I've been semi wrestling trying to get coaster's to save properly, because for some reason it doesn't like to save the right entity in its dtvars.
It's on my todo list, thanks!

**Comment by Thepootisman** [comment]
Alright, thanks buddy, keep up the good work, hopefully getting it to work won't be too much trouble for ya', Good luck for the future with this mod, stay awesome!
